modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]]
modId="hardernaturalhealing"
version="${file.jarVersion}"
displayName="Harder Natural Healing Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-natural-healing"
updateJSONURL="https://raw.githubusercontent.com/mactso/HarderNaturalHealing/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Natural Healing Mod.'
[[dependencies.hardernaturalhealing]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardernaturalhealing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="SERVER"
